name: powergrid-env
dependencies:
- openssl=1.0.2f=0
- pip=8.0.2=py27_0
- python=2.7.11=0
- readline=6.2=2
- setuptools=19.6.2=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - alembic==0.8.4
  - bcrypt==2.0.0
  - beautifulsoup4==4.4.1
  - blinker==1.4
  - cffi==1.5.0
  - cssmin==0.2.0
  - dominate==2.1.16
  - factory-boy==2.6.0
  - fake-factory==0.5.3
  - flake8==2.5.0
  - flake8-blind-except==0.1.0
  - flake8-debugger==1.4.0
  - flake8-docstrings==0.2.1.post1
  - flake8-isort==0.2
  - flake8-quotes==0.1.1
  - flask==0.10.1
  - flask-admin==1.4.0
  - flask-assets==0.11
  - flask-bcrypt==0.7.1
  - flask-bootstrap==3.3.5.7
  - flask-cache==0.13.1
  - flask-debugtoolbar==0.10.0
  - flask-flatpages==0.6
  - flask-gravatar==0.4.2
  - flask-login==0.3.2
  - flask-mail==0.9.1
  - flask-migrate==1.7.0
  - flask-pymongo==0.4.0
  - flask-restless==0.17.0
  - flask-script==2.0.5
  - flask-sqlalchemy==2.1
  - flask-themes==0.1.3
  - flask-uploads==0.2.0
  - flask-wtf==0.12
  - gunicorn==19.4.5
  - isort==4.2.2
  - itsdangerous==0.24
  - jinja2==2.8
  - jsmin==2.2.0
  - mako==1.0.3
  - markdown==2.6.5
  - markupsafe==0.23
  - mccabe==0.3.1
  - mimerender==0.5.5
  - pep257==0.7.0
  - pep8==1.7.0
  - pep8-naming==0.3.3
  - py==1.4.31
  - pycparser==2.14
  - pyflakes==1.0.0
  - pymongo==3.2.1
  - pytest==2.8.2
  - python-dateutil==2.4.2
  - python-editor==0.5
  - python-mimeparse==1.5.1
  - pyyaml==3.11
  - six==1.10.0
  - sqlalchemy==1.0.11
  - visitor==0.1.2
  - waitress==0.8.10
  - webassets==0.11.1
  - webob==1.5.1
  - webtest==2.0.20
  - werkzeug==0.11.3
  - wtforms==2.1

